In [1]:
import sys
import os
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
sys.path.insert(1, os.path.join(sys.path[0], '/Users/henryxu/Desktop/Research/prismio'))
from prismio.io_frame import IOFrame
# from prismio.io_frame_plotter import IOFramePlotter
import seaborn as sns
import prismio.models
import prismio

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [2]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
import prismio.models

## using io_time as metric

In [3]:
models = [
    [LogisticRegression(), 'MinMaxScaler'],
    [LogisticRegression(), 'Original data'],
    [DecisionTreeClassifier(), 'Original data'],
    [KNeighborsClassifier(n_neighbors=3), 'MinMaxScaler'],
    [SVC(kernel="linear", C=0.025), 'MinMaxScaler'],
    [SVC(gamma=2, C=1), 'MinMaxScaler'],
    [GaussianProcessClassifier(1.0 * RBF(1.0)), 'MinMaxScaler'],
    [RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1), 'Original data'],
    [MLPClassifier(hidden_layer_sizes=(100,100), max_iter=1000, alpha=0.1), 'MinMaxScaler'],
    [AdaBoostClassifier(), 'MinMaxScaler'],
    [GaussianNB(), 'Original data'],
    [QuadraticDiscriminantAnalysis(), 'MinMaxScaler']
]

In [4]:
parameters = ['transfer_size', 'num_proc']
X, y = prismio.models.prepare_data_allocate_cori_bb(
    parameters, 
    "/Users/henryxu/Desktop/paper/papers-2021-prismio/data/model/ior-cori-io-info.csv", 
    metric='io_time', 
    optimization='min'
)
minmax_normalized_X, y = prismio.prepare_data_allocate_cori_bb(
    parameters, 
    "/Users/henryxu/Desktop/paper/papers-2021-prismio/data/model/ior-cori-io-info.csv", 
    metric='io_time', 
    optimization='min',
    normalize_independent_variables=MinMaxScaler
)
standardized_X, y = prismio.models.prepare_data_allocate_cori_bb(
    parameters, 
    "/Users/henryxu/Desktop/paper/papers-2021-prismio/data/model/ior-cori-io-info.csv", 
    metric='io_time', 
    optimization='min',
    normalize_independent_variables=StandardScaler
)


print(X)
print(y)
print("=================================")
print()

for model in models:
    print(type(model[0]).__name__ + ", " + model[1] + ":")
    if model[1] == 'MinMaxScaler':
        mymodel = prismio.models.get_model(minmax_normalized_X, y, model[0], k=5)
    elif model[1] == 'StandardScaler':
        mymodel = prismio.models.get_model(standardized_X, y, model[0], k=5)
    else:
        mymodel = prismio.models.get_model(X, y, model[0], k=5)    
    print("prediction on traning data:")
    print(mymodel.predict(X))
    print("=================================")
    print()
    
    

[[  65536      64]
 [  65536     128]
 [  65536     256]
 [  65536     512]
 [  65536    1024]
 [   4096      64]
 [   4096     128]
 [   4096     256]
 [   4096     512]
 [   4096    1024]
 [1048576      64]
 [1048576     128]
 [1048576     256]
 [1048576     512]
 [1048576    1024]]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 16]

LogisticRegression, MinMaxScaler:


/Users/henryxu/miniconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
1 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/henryxu/miniconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/henryxu/miniconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py", line 1554, in fit
    raise ValueError(
ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 0

  warnings.warn(some_fits_failed_messag

Validation Accuracy -- avg: nan, max: nan, min: nan, std: nan
prediction on traning data:
[16 16 16 16 16 16 16 16 16 16 16 16 16 16 16]

LogisticRegression, Original data:


/Users/henryxu/miniconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
1 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/henryxu/miniconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/henryxu/miniconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py", line 1554, in fit
    raise ValueError(
ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 0

  warnings.warn(some_fits_failed_messag

Validation Accuracy -- avg: nan, max: nan, min: nan, std: nan
prediction on traning data:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

DecisionTreeClassifier, Original data:
Validation Accuracy -- avg: 0.933, max: 1.000, min: 0.667, std: 0.133
prediction on traning data:
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 16]

KNeighborsClassifier, MinMaxScaler:
Validation Accuracy -- avg: 0.933, max: 1.000, min: 0.667, std: 0.133
prediction on traning data:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

SVC, MinMaxScaler:


/Users/henryxu/miniconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
1 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/henryxu/miniconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/henryxu/miniconda3/lib/python3.9/site-packages/sklearn/svm/_base.py", line 199, in fit
    y = self._validate_targets(y)
  File "/Users/henryxu/miniconda3/lib/python3.9/site-packages/sklearn/svm/_base.py", line 720, in _validate_targets
    raise ValueError(
ValueError: The n

Validation Accuracy -- avg: nan, max: nan, min: nan, std: nan
prediction on traning data:
[16 16 16 16 16 16 16 16 16 16 16 16 16 16 16]

SVC, MinMaxScaler:
Validation Accuracy -- avg: nan, max: nan, min: nan, std: nan
prediction on traning data:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

GaussianProcessClassifier, MinMaxScaler:
Validation Accuracy -- avg: nan, max: nan, min: nan, std: nan
prediction on traning data:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

RandomForestClassifier, Original data:
Validation Accuracy -- avg: 0.933, max: 1.000, min: 0.667, std: 0.133
prediction on traning data:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

MLPClassifier, MinMaxScaler:
Validation Accuracy -- avg: 0.933, max: 1.000, min: 0.667, std: 0.133
prediction on traning data:
[16 16 16 16 16 16 16 16 16 16 16 16 16 16 16]

AdaBoostClassifier, MinMaxScaler:
Validation Accuracy -- avg: 0.800, max: 1.000, min: 0.667, std: 0.163
prediction on traning data:
[16 16 16 16 16 16 16 16 16 16 16 16 16 16 16]

GaussianNB, Original data:
Vali

/Users/henryxu/miniconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/henryxu/miniconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/henryxu/miniconda3/lib/python3.9/site-packages/sklearn/discriminant_analysis.py", line 869, in fit
    raise ValueError(
ValueError: y has only 1 sample in class 16, covariance is ill defined.

--------------------------------------------------------------------------------
1

ValueError: y has only 1 sample in class 16, covariance is ill defined.

## using io_bandwidth as metric

In [ ]:
models = [
    [LogisticRegression(), 'MinMaxScaler'],
    [LogisticRegression(), 'Original data'],
    [DecisionTreeClassifier(), 'Original data'],
    [KNeighborsClassifier(n_neighbors=3), 'MinMaxScaler'],
    [SVC(kernel="linear", C=0.025), 'MinMaxScaler'],
    [SVC(gamma=2, C=1), 'MinMaxScaler'],
    [GaussianProcessClassifier(1.0 * RBF(1.0)), 'MinMaxScaler'],
    [RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1), 'Original data'],
    [MLPClassifier(hidden_layer_sizes=(100,100), max_iter=1000, alpha=0.1), 'MinMaxScaler'],
    [AdaBoostClassifier(), 'MinMaxScaler'],
    [GaussianNB(), 'Original data'],
    [QuadraticDiscriminantAnalysis(), 'MinMaxScaler']
]

In [5]:
parameters = ['transfer_size', 'num_proc']
X, y = prismio.models.prepare_data_allocate_cori_bb(
    parameters, 
    "/Users/henryxu/Desktop/paper/papers-2021-prismio/data/model/ior-cori-io-info.csv", 
    metric='io_bandwidth', 
    optimization='max'
)
minmax_normalized_X, y = prismio.prepare_data_allocate_cori_bb(
    parameters, 
    "/Users/henryxu/Desktop/paper/papers-2021-prismio/data/model/ior-cori-io-info.csv", 
    metric='io_bandwidth', 
    optimization='max',
    normalize_independent_variables=MinMaxScaler
)
standardized_X, y = prismio.models.prepare_data_allocate_cori_bb(
    parameters, 
    "/Users/henryxu/Desktop/paper/papers-2021-prismio/data/model/ior-cori-io-info.csv", 
    metric='io_bandwidth', 
    optimization='max',
    normalize_independent_variables=StandardScaler
)

print(X)
print(y)
print("=================================")
print()

for model in models:
    print(type(model[0]).__name__ + ", " + model[1] + ":")
    if model[1] == 'MinMaxScaler':
        mymodel = prismio.models.get_model(minmax_normalized_X, y, model[0], k=5)
    elif model[1] == 'StandardScaler':
        mymodel = prismio.models.get_model(standardized_X, y, model[0], k=5)
    else:
        mymodel = prismio.models.get_model(X, y, model[0], k=5)    
    print("prediction on traning data:")
    print(mymodel.predict(X))
    print("=================================")
    print()
    
    

[[  65536      64]
 [  65536     128]
 [  65536     256]
 [  65536     512]
 [  65536    1024]
 [   4096      64]
 [   4096     128]
 [   4096     256]
 [   4096     512]
 [   4096    1024]
 [1048576      64]
 [1048576     128]
 [1048576     256]
 [1048576     512]
 [1048576    1024]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

LogisticRegression, MinMaxScaler:
Validation Accuracy -- avg: nan, max: nan, min: nan, std: nan


/Users/henryxu/miniconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/Users/henryxu/miniconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/henryxu/miniconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py", line 1554, in fit
    raise ValueError(
ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 0

  warnings.warn(some_fits_failed_messag

ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 0